# Serverless Config
service:
  name: harbinger-poster

# Plugins
plugins:
  - serverless-webpack

# Provider
provider:
  name: aws
  runtime: nodejs12.x
  apiKeys:
    - ${opt:stage,'testnet'}
  memorySize: 256
  timeout: 30

  stage: ${opt:stage,'testnet'}
  region: eu-west-1

  # Environment Variables
  environment:
    AWS_KMS_KEY_ID: ${ssm:${self:custom.awsKmsKeyId.${self:provider.stage}}~true}
    AWS_KMS_KEY_REGION: ${self:custom.awsKmsKeyRegion.${self:provider.stage}}
    ORACLE_CONTRACT_ADDRESS: ${ssm:${self:custom.oracleContractAddress.${self:provider.stage}}~true}
    NODE_ADDR: ${self:custom.nodeAddr.${self:provider.stage}}
    COINBASE_API_KEY_ID: ${ssm:${self:custom.coinbaseApiKeyId.${self:provider.stage}}~true}
    COINBASE_API_KEY_SECRET: ${ssm:${self:custom.coinbaseApiKeySecret.${self:provider.stage}}~true}
    COINBASE_API_KEY_PASSPHRASE: ${ssm:${self:custom.coinbaseApiKeyPassphrase.${self:provider.stage}}~true}
    ASSETS: ${self:custom.assets.${self:provider.stage}}

# Custom Variables
custom:
  stages:
    - testnet
    - mainnet
  # AWS KMS Key ID.
  awsKmsKeyId:
    testnet: "/tezos/testnet-kms-key-id"
    mainnet: "/tezos/mainnet-kms-key-id"
  # AWS Region where AWS KMS Key is located.
  awsKmsKeyRegion:
    testnet: "eu-west-1"
    mainnet: "eu-west-1"
  # The address of the Oracle Contract.
  oracleContractAddress:
    testnet: "/tezos/testnet-contract-address"
    mainnet: "/tezos/mainnet-contract-address"
  # The address of a node.    
  nodeAddr:
    testnet: "https://rpctest.tzbeta.net"
    mainnet: "https://rpc.tzbeta.net"
  # A Coinbase Pro API Key ID
  coinbaseApiKeyId:
    testnet: "/tezos/testnet-pro-api-key"
    mainnet: "/tezos/mainnet-pro-api-key"
  # A Coinbase Pro API Key Secret
  coinbaseApiKeySecret:
    testnet: "/tezos/testnet-pro-api-secret"
    mainnet: "/tezos/mainnet-pro-api-secret"
  # A Coinbase Pro API Key Passphase
  coinbaseApiKeyPassphrase:
    testnet: "/tezos/testnet-pro-api-passphrase"
    mainnet: "/tezos/mainnet-pro-api-passphrase"
  # Assets to update.
  assets:        
    testnet: "BAT-USDC,BTC-USD,COMP-USD,DAI-USDC,ETH-USD,KNC-USD,LINK-USD,REP-USD,XTZ-USD,ZRX-USD"
    mainnet: "BAT-USDC,BTC-USD,COMP-USD,DAI-USDC,ETH-USD,KNC-USD,LINK-USD,REP-USD,XTZ-USD,ZRX-USD"

# Functions
functions:
  autoUpdateOracle:
    handler: handler.updateOracle
    reservedConcurrency: 1
    events:
      - schedule: rate(5 minutes)
  manualUpdateOracle:
    handler: handler.updateOracle      
    events:
      - http:
          method: get
          path: update
          private: true
  getInfo:
    handler: handler.info
    events:
      - http:
          method: get
          path: info
          private: true
